# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
jobs:
- job: init
  steps:
  - template: .azure/templates/steps/setup-npm.yml
  - script: mkdir build && echo "something something" > build/artefact.txt
    displayName: pseudo build artifacts
  - publish: $(Build.SourcesDirectory)/build
    artifact: app
    displayName: Persist build
- job: generator
  steps:
  - bash: |
      echo "##vso[task.setVariable variable=test_strategy;isOutput=true]$(jq -n -c '[range(1;13) | {(["shard", .|tostring ] | join("")) : {"shard" : .|tostring} }] | add')"
    name: mtrx
- job: runner
  dependsOn: 
  - generator
  - init
  strategy:
    matrix: $[ dependencies.generator.outputs['mtrx.test_strategy'] ]
  steps:
    - download: current
      artifact: app
    - script: |
        mv $(Pipeline.Workspace)/app ./build
        ls
        cat build/artefact.txt
      displayName: show persistence
    - template: .azure/templates/steps/setup-npm.yml
    - script: npx jest --shard $(shard)/12
      displayName: jest tests shard \#$(shard)
  